### PR TITLE
fix when move or ask error will not try conn to the addr get

### PR DESCRIPTION
**Pull request by july2993**
if node A return -MOVE  B  

we shoud try commad on node B,the preview implemtation will pick a client , node B or a ramdom node from pools if not associate pool to node B.

it 's easy to happen when there is a new node(not in the pools), then it will pick a random node again and again...endless(MOVE B, get random node, get MOVE B again....note it will not set node B to has tried)

you can send a cluster failover to a slave, and then this will happen.

here's my test code, just set and get a random key,you can run it and send cluster failover to a slave to trigger Manual failover.
```go
package main

import (
    "fmt"
    "math/rand"
    "os"
    "os/signal"
    "strconv"
    "syscall"
    "time"

    "github.com/fzzy/radix/extra/cluster"
)

var writeCount = 0 
var failCount = 0 

func setGetLoop() {
    cluster, err := cluster.NewCluster("127.0.0.1:7000")
    if err != nil {
        panic(err)
    }   

    for {
        time.Sleep(time.Millisecond * 100)
        key := strconv.FormatInt(int64(rand.Int()), 10) 
        err := cluster.Cmd("set", key, key).Err
        if err != nil {
            fmt.Println(err)
            fmt.Println("\n")
            failCount++
            continue
        }   

        get, getErr := cluster.Cmd("get", key).Str()
        if getErr != nil {
            fmt.Println(getErr)
            fmt.Println("\n")
            failCount++
            continue
        }   

        writeCount++

        fmt.Println("set and get back ", get)
    }   
}

func main() {
    go setGetLoop()
    c := make(chan os.Signal)
    signal.Notify(c, os.Interrupt, os.Kill, syscall.SIGTERM, syscall.SIGHUP)
    <-c
    fmt.Println("wirte ", writeCount, " fail ", failCount)
}
```

### CODE REVIEW

**Comment by mediocregopher** [comment]
Wow, thanks for the detailed bug report. I'll double check what's happening, what *should* happen is if node B isn't in the pool it should call Reset and then try again. I'll look into it more right now, and hopefully we can get this merged in :)

**Comment by mediocregopher** [comment]
So I've looked into this some more, and I'm not sure I'm seeing the same problem you're seeing. I have a 6 node cluster set up, 3 masters and 3 slaves, and when I kill one of the masters this is the output I see

```
2015/02/21 13:30:23 setting 8121576815539813105
2015/02/21 13:30:23 setting 2740376916591569721
2015/02/21 13:30:24 setting 8249030965139585917
2015/02/21 13:30:24 Cluster doesn't make sense
2015/02/21 13:30:24

2015/02/21 13:30:24 setting 898860202204764712
2015/02/21 13:30:24 Cluster doesn't make sense
2015/02/21 13:30:24

2015/02/21 13:30:24 setting 9010467728050264449
2015/02/21 13:30:24 setting 685213522303989579
2015/02/21 13:30:24 setting 2050257992909156333
2015/02/21 13:30:24 Cluster doesn't make sense
2015/02/21 13:30:24

2015/02/21 13:30:24 setting 6281838661429879825
2015/02/21 13:30:24 setting 2227583514184312746
2015/02/21 13:30:24 setting 2873287401706343734
2015/02/21 13:30:24 Cluster doesn't make sense
2015/02/21 13:30:24

2015/02/21 13:30:24 setting 8603989663476771718
2015/02/21 13:30:24 Cluster doesn't make sense
2015/02/21 13:30:24

2015/02/21 13:30:24 setting 6842348953158377901
2015/02/21 13:30:25 setting 7388428680384065704
2015/02/21 13:30:25 setting 6735196588112087610
2015/02/21 13:30:25 dial tcp 127.0.0.1:7000: too many open files
2015/02/21 13:30:25

2015/02/21 13:30:25 setting 1687184559264975024
2015/02/21 13:30:25 setting 3950896730125624717
2015/02/21 13:30:25 setting 8273290538659802269
2015/02/21 13:30:25 dial tcp 127.0.0.1:7000: too many open files
2015/02/21 13:30:25

2015/02/21 13:30:25 setting 6296367092202729479
2015/02/21 13:30:26 dial tcp 127.0.0.1:7000: too many open files
2015/02/21 13:30:26

2015/02/21 13:30:26 setting 9029029644282286269
```

So there's a couple `Cluster doesn't make sense` errors, which makes sense because at that point the cluster hasn't elected a master for those slots yet, so there's not much which can be done but keep waiting. There is definitely an error though, because at this point for some reason radix starts creating tons of connections, eventually running out of file descriptors. I'm going to investigate this but further, but I just wanted to let you know where I'm at.

**Comment by mediocregopher** [comment]
I take it back, I do see the infinite loop now. Looking into it

**Comment by mediocregopher** [comment]
So I found a more elegant solution to the problem which didn't involve messing with the `Reset` methods, as well as made putting connections back in their pool more reliable so it's not as likely we'll get those file descriptor errors in the future. I've pushed my change to the [cluster_fix](https://github.com/mediocregopher/radix.v2/tree/cluster_fix) branch, let me know how they work for you.

**Comment by july2993** [comment]
I did messing with the Rest...and it's bad.
However, i think when you get a MOVE error to addr B, at least you shoud try to connect to addr B, if you can't connect to addr B, it means somethink error with the cluster, it would be pretty sure get somethink error even you try a random node again. The purpose of Reset is to refresh the whole cluster status(mapping the slot to the right addr, reduce the MOVE error)

in my test i has 3 master and 3 slave.
```
M: ab764d481e4511dabb3718d2e8b2c74871d7c1c8 127.0.0.1:7000
   slots:0-5902,7056,10923-10979 (5961 slots) master
   1 additional replica(s)
S: d2341e98b1f89b11fac84ffeba27ece73db046e5 127.0.0.1:7004
   slots: (0 slots) slave
   replicates 3de5920a64fef29b8352f5936009943e6c44a041
M: 9b60a8ad278d327e00d4b05cdd3db4a99786cf0e 127.0.0.1:7002
   slots:10980-16383 (5404 slots) master
   1 additional replica(s)
M: 3de5920a64fef29b8352f5936009943e6c44a041 127.0.0.1:7001
   slots:5903-7055,7057-10922 (5019 slots) master
   1 additional replica(s)
S: b67b06dc3776fa0dad502e80310945abdcdfc8fa 127.0.0.1:7005
   slots: (0 slots) slave
   replicates 9b60a8ad278d327e00d4b05cdd3db4a99786cf0e
S: f801a0c5acd45bc9730d4ae01a72d1f6cac96046 127.0.0.1:7003
   slots: (0 slots) slave
   replicates ab764d481e4511dabb3718d2e8b2c74871d7c1c8
[OK] All nodes agree about slots configuration.
>>> Check for open slots...
>>> Check slots coverage...
```

i send "cluster failover" to 3 slave one by one 
```
echo "cluster failover" | ./redis-cli -c -h 127.0.0.1 -p 7003
sleep 2
echo "cluster failover" | ./redis-cli -c -h 127.0.0.1 -p 7004
sleep 2
echo "cluster failover" | ./redis-cli -c -h 127.0.0.1 -p 7005
```

at the meantime,  some command failed which , because it did not try connected to the nodes which it 's told to MOVE to.

"reset try" means it call Reset
"reset true" means it do Reset reset the cluster status by a random node(because the resetThrottle it might return nil directly)
```
reset try
Cluster doesn't make sense, 127.0.0.1:7003 might be gone

reset try
Cluster doesn't make sense, 127.0.0.1:7004 might be gone

....
....

reset try
Cluster doesn't make sense, 127.0.0.1:7004 might be gone

reset try
Cluster doesn't make sense, 127.0.0.1:7003 might be gone

reset try
ok  2015-02-23 00:47:22.637551213 +0800 CST
reset true
wirte  73885  fail  1332
```

**Comment by mediocregopher** [comment]
Ok, I missed that case. Yeah, during a manual failover it wasn't doing its best. I made the following changes in the [cluster_fix](https://github.com/fzzy/radix/tree/cluster_fix) branch:

* Simplified moved logic a bit, it will always call reset in the case of a `MOVED` or `ASK` now

* Made `getConn` attempt to create a pool if one is not currently made for the passed in address. The pool creation is throttled in a similar way to Reset, except on a per address basis. The effect here is that when the `MOVED` msg is parsed and the new address found the pool for that address is immediately (attempted to be) made

I've tested the manual failover case with these changes and it appears well-behaved to me, as well as the test where I just kill one of the masters. Let me know if these changes work for you, and thanks for the detailed bug report so far :)

**Comment by july2993** [comment]
work well now in my test, no commands fail while manual failover.

**Comment by mediocregopher** [comment]
Good to hear! v0.5.4 is up on master, which includes the fixes from here. Sorry we couldn't get your code merged in, but thank you for the really detailed bug report :) Gonna close this now, feel free to open a new pr/issue if you have any other problems

**Pull request closed without merging**
